export type ExpenseType = {
    instanceId: number,
    instanceType: string,
    livingExpense: number,
    creditCard: number,
    residenceOwnerCorporation: number,
    residenceOwnerCorporationFreq: string,
    privateSchool: number,
    privateSchoolFreq: string,
    childCare: number,
    childCareFreq: string,
    healthInsurance: number,
    healthInsuranceFreq: string,
    incomeProtection: number,
    incomeProtectionFreq: string,
    childSupport: number,
    childSupportFreq: string,
}

export const initialExpense: ExpenseType = {
    instanceId: 1,
    instanceType: 'expenses',
    livingExpense: 0,
    creditCard: 0,
    residenceOwnerCorporation: 0,
    residenceOwnerCorporationFreq: 'Annually',
    privateSchool: 0,
    privateSchoolFreq: 'Annually',
    childCare: 0,
    childCareFreq: 'Annually',
    healthInsurance: 0,
    healthInsuranceFreq: 'Annually',
    incomeProtection: 0,
    incomeProtectionFreq: 'Annually',
    childSupport: 0,
    childSupportFreq: 'Annually',
}